export const getImageSource = (symbol) => {
  switch (symbol) {
    case 'BTC':
      return require('../assets/crypto/btc.png');
    case 'ETH':
      return require('../assets/crypto/eth.png');
    case 'LINK':
      return require('../assets/crypto/link.png');
    case 'ETC':
      return require('../assets/crypto/etc.png');
    case 'EOS':
      return require('../assets/crypto/eos.png');
    case 'LTC':
      return require('../assets/crypto/ltc.png');
    case 'BCH':
      return require('../assets/crypto/bch.png');
    case 'BNB':
      return require('../assets/crypto/bnb.png');
    case 'BSV':
      return require('../assets/crypto/bsv.png');
    case 'XTZ':
      return require('../assets/crypto/xtz.png');
    case 'XRP':
      return require('../assets/crypto/xrp.png');
    case 'ALGO':
      return require('../assets/crypto/algo.png');
    case 'MATIC':
      return require('../assets/crypto/matic.png');
    case 'OKB':
      return require('../assets/crypto/okb.png');
    case 'HT':
      return require('../assets/crypto/ht.png');
    case 'ATOM':
      return require('../assets/crypto/atom.png');
    case 'TRX':
      return require('../assets/crypto/trx.png');
    case 'PAXG':
      return require('../assets/crypto/pax.png');
    case 'ADA':
      return require('../assets/crypto/ada.png');
    case 'USDT':
      return require('../assets/crypto/usdt.png');
    case 'DRGN':
      return require('../assets/crypto/drgn.png');
    case 'DOGE':
      return require('../assets/crypto/doge.png');
    case 'TOMO':
      return require('../assets/crypto/tomo.png');
    case 'BTMX':
      return require('../assets/crypto/btmx.png');
    case 'TRYB':
      return require('../assets/crypto/tryb.png');
    case 'LEO':
      return require('../assets/crypto/leo.png');
    case 'FTT':
      return require('../assets/crypto/ftt.png');
    case 'FTT_R3':
      return require('../assets/crypto/ftt.png');
    case 'FTT_TT1':
      return require('../assets/crypto/ftt.png');
    case 'FTT_TT2':
      return require('../assets/crypto/ftt.png');
    case 'USD':
      return require('../assets/crypto/usd.png');
    case 'EUR':
      return require('../assets/crypto/eur.png');
    case 'BRZ':
      return require('../assets/crypto/brz.png');
    case 'BRL':
      return require('../assets/crypto/brl.png');
    case 'KNC':
      return require('../assets/crypto/knc.png');
    case 'WRX':
      return require('../assets/crypto/wrx.png');
    case 'THETA':
      return require('../assets/crypto/theta.png');
    case 'XAUT':
      return require('../assets/crypto/xaut.png');
    case 'COMP':
      return require('../assets/crypto/comp.svg');
    case 'BAL':
      return require('../assets/crypto/bal.svg');
    case 'TRUMPWIN':
      return require('../assets/crypto/trumpwin.png');
    case 'TRUMPLOSE':
      return require('../assets/crypto/trumplose.png');
    case 'SRM':
      return require('../assets/crypto/srm.svg');
    case 'MSRM':
      return require('../assets/crypto/msrm.svg');
    case 'SRM_LOCKED':
      return require('../assets/crypto/srm.svg');
    case 'MSRM_LOCKED':
      return require('../assets/crypto/msrm.svg');
    case 'SXP':
      return require('../assets/crypto/sxp.png');
    case 'SOL':
      return require('../assets/crypto/sol.png');
    case 'YFI':
      return require('../assets/crypto/yfi.svg');
    case 'RUNE':
      return require('../assets/crypto/rune.png');
    case 'AMPL':
      return require('../assets/crypto/ampl.png');
    case 'WBTC':
      return require('../assets/crypto/wbtc.png');
    case 'MKR':
      return require('../assets/crypto/mkr.png');
    case 'DMG':
      return require('../assets/crypto/dmm.png');
    case 'UBXT':
      return require('../assets/crypto/ubxt.png');
    case 'UNI':
      return require('../assets/crypto/uni.png');
    case 'LEND':
      return require('../assets/crypto/aave.png');
    case 'CREAM':
      return require('../assets/crypto/cream.png');
    case 'HGET':
      return require('../assets/crypto/hdget.png');
    case 'HNT':
      return require('../assets/crypto/hnt.png');
    case 'MTA':
      return require('../assets/crypto/mstable.png');
    case 'SUSHI':
      return require('../assets/crypto/sushi.png');
    case 'FRONT':
      return require('../assets/crypto/front.png');
    case 'ALEPH':
      return require('../assets/crypto/aleph.png');
    case 'USDC':
      return require('../assets/crypto/usdc.png');
    default:
      return require('../assets/crypto/other.png');
  }
};
